/* Production build.
 *   node scripts/build.js
 * Reads .env, writes config into extension/ and web/, and packages
 * dist/jobflow-extension-<version>.zip for the Chrome Web Store. */
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const root = path.join(__dirname, '..');
const envFile = path.join(root, '.env');
if (!fs.existsSync(envFile)) {
  console.error('Missing .env - copy .env.example to .env and fill it in.');
  process.exit(1);
}
const env = Object.fromEntries(fs.readFileSync(envFile, 'utf8').split('\n')
  .map((l) => l.trim()).filter((l) => l && !l.startsWith('#') && l.includes('='))
  .map((l) => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^["']|["']$/g, '')]; }));

const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'WEB_APP_URL', 'CHROME_STORE_URL', 'SUPPORT_EMAIL'];
const bad = required.filter((k) => !env[k] || /paste-your|your-domain|your-extension-id/.test(env[k]));
if (bad.length) {
  console.error(`Fill these in .env first: ${bad.join(', ')}`);
  process.exit(1);
}
if (env.OPENROUTER_API_KEY) console.warn('Note: OPENROUTER_API_KEY in .env is ignored by the build (it must stay server-side).');
if (/service_role/.test(Buffer.from((env.SUPABASE_ANON_KEY.split('.')[1] || ''), 'base64').toString())) {
  console.error('SUPABASE_ANON_KEY looks like a service-role key. Use the anon public key.');
  process.exit(1);
}

const q = (v) => JSON.stringify(v);
fs.writeFileSync(path.join(root, 'extension/config.js'),
`/* Generated by scripts/build.js - public values only (protected by Row Level Security). */
self.JOBFLOW_CONFIG = {
  supabaseUrl: ${q(env.SUPABASE_URL)},
  supabaseAnonKey: ${q(env.SUPABASE_ANON_KEY)},
  webAppUrl: ${q(env.WEB_APP_URL.replace(/\/$/, ''))},
  supportEmail: ${q(env.SUPPORT_EMAIL)}
};
`);
fs.writeFileSync(path.join(root, 'web/config.js'),
`/* Generated by scripts/build.js - public values only (protected by Row Level Security). */
window.JOBFLOW_CONFIG = {
  supabaseUrl: ${q(env.SUPABASE_URL)},
  supabaseAnonKey: ${q(env.SUPABASE_ANON_KEY)},
  chromeStoreUrl: ${q(env.CHROME_STORE_URL)},
  supportEmail: ${q(env.SUPPORT_EMAIL)},
  companyName: 'JobFlow AI'
};
`);

require('./sync-shared.js');

// Tighten host permissions to this Supabase project
const manifestPath = path.join(root, 'extension/manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
manifest.host_permissions = [`${new URL(env.SUPABASE_URL).origin}/*`];
fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

const dist = path.join(root, 'dist');
fs.mkdirSync(dist, { recursive: true });
const zipPath = path.join(dist, `jobflow-extension-${manifest.version}.zip`);
fs.rmSync(zipPath, { force: true });
try {
  execFileSync('zip', ['-qr', zipPath, '.', '-x', '*.DS_Store'], { cwd: path.join(root, 'extension') });
} catch (err) {
  console.error('Could not run `zip`. Zip the extension/ folder manually for the Chrome Web Store.');
  process.exit(1);
}
console.log(`Built ${path.relative(root, zipPath)} (${Math.round(fs.statSync(zipPath).size / 1024)} KB)`);
console.log('Deploy web/ to Vercel or Netlify, and upload the zip to the Chrome Web Store.');
